# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HIaWB-PM7rTZrVkSBmhkw1E-Faed6akM
"""
if uploaded_file is not None:

    # Leer archivo sin perder encabezados
    df = pd.read_csv(uploaded_file, sep=None, engine="python")

    st.success("✅ Archivo cargado correctamente.")
    
    # Limpiar espacios en nombres de columnas
    df.columns = df.columns.str.strip()

    # Identificar columnas NO numéricas (las que no se deben tocar)
    columnas_no_numericas = ['Categoria', 'Aviso']

    # Identificar columnas numéricas automáticamente (todas menos las anteriores)
    columnas_numericas = [col for col in df.columns if col not in columnas_no_numericas]

    # Convertir columnas numéricas correctamente
    for col in columnas_numericas:
        df[col] = (
            df[col]
            .astype(str)
            .str.replace(",", ".", regex=False)   # coma → punto decimal
        )
        df[col] = pd.to_numeric(df[col], errors='coerce')  # forzar numérico sin eliminar filas

    # Mostrar info resumida
    st.write("### Vista previa de los datos (primeras filas)")
    st.dataframe(df.head())

    st.write(f"**Columnas numéricas detectadas:** {len(columnas_numericas)}")
    st.write(columnas_numericas)

    st.write(f"**Columnas categóricas detectadas:** {columnas_no_numericas}")

